apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liteagent

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0"

images:
  - name: liteagent-api
    newTag: latest
  - name: liteagent-worker
    newTag: latest
